[package]
name = "axum-server"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
axum = { version = "0.6.20", default-features = false, features = ["macros"] }
tower-service = "0.3.2"
wasi-hyperium = { path = "../.." }
wit-bindgen = "0.14.0"
